sudo: required
language: node_js
services:
    - docker
    
before_install:
    - docker build -t n4ybn/docker-react -f Dockerfile.dev .

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-570317715919"
    bucket_path: "docker-react"
    on:
        branch: master
        access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY